#!/bin/bash

NOW=`date +%Y%m%d_%H%M%S`
DESTDIR=/tmp/www
ZIPDIR=${DESTDIR}/website_$NOW
DESTDIR_HTML=${DESTDIR}/html_$NOW

# make a working dir
mkdir -p $ZIPDIR
# go to the working directory
cd $ZIPDIR

# get the latest version from github
wget https://github.com/nova-labs/website/archive/master.zip -O master.zip

# unzip the website zipfile
unzip master.zip

# move the new site to the production location
mv website-master/html $DESTDIR_HTML
mv -f website-master/deploy_html $DESTDIR/deploy_html

cd $DESTDIR

if [ ! -L html ]; then
    if [ -d html ]; then
        # Legacy html directory that's not a symlink
        mv html html.legacy
    else
        # no idea wtf this is, but move it out of the way
        mv html html_$NOW.wtf
    fi
fi

# make the symlink, replacing an existing one if necessary
ln -snf html_$NOW html

# clean up leftovers
rm -rf $ZIPDIR

