#!/usr/bin/perl -w
use strict; use warnings;
use CGI;
use Data::Dumper;

my $cgi = CGI->new;

my @pathinfo = split( '/', $cgi->path_info );
shift( @pathinfo ) until $pathinfo[0];

my $list = $cgi->param( 'list' ) || shift( @pathinfo );
my $email = $cgi->param( 'email' ) || shift( @pathinfo );

print $cgi->header( 'text/html' );
print $cgi->start_html( 'Unsubscribe' );

if ( $list && $email ) {
    my @lists = ();
    if ( lc( $list ) eq 'all' ) {
        open( my $fh, '-|', '/usr/lib/mailman/bin/find_member', $email )
            or die "Cannot run find_member: $!";
        while ( local $_ = <$fh> ) {
            next unless s/^\s+//;
            chomp;
            push( @lists => $_ );
        }
    } else {
        push( @lists => $list );
    }
    print "<p>Unsubscribe complete.</p>";
} else {
print <<'END';
<p>Invalid arguments.  For help please email
<a href="mailto:help@nova-labs.org">help@nova-labs.org</a>.
</p>
END

print $cgi->end_html;
